honours_project/honours_project/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('media_app.urls')),
    path('admin/', admin.site.urls),
]

honours_project/media_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('login/', views.login_view, name='login'),
    path('register', views.register_request, name='register'),
    path('logout/', views.logout_view, name='logout'),
    path('search/', views.search_media, name='search_media'),
    path('add-to-list/', views.add_to_list, name='add_to_list'),
    path('remove-from-list/<int:medialist_id>/<int:media_id>/', views.remove_from_list, name='remove_from_list'),
    path('add-rating/', views.add_rating, name='add_rating'),
    path('recommend/', views.recommend_media, name='recommend_media'),
    path('ratings/', views.ratings, name='ratings'),
]

honours_project/media_app/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import MinValueValidator, MaxValueValidator

# Create your models here.

class Media(models.Model):
    title = models.CharField(max_length=255)
    description = models.TextField(blank=True)
    media_type = models.CharField(max_length=50)
    poster_url = models.URLField(blank=True)

    def __str__(self):
        return self.title

class MediaList(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    media = models.ManyToManyField('Media')

class Ratings(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    media = models.ForeignKey(Media, on_delete=models.CASCADE)
    score = models.IntegerField(validators=[MinValueValidator(0), MaxValueValidator(10)])

honours_project/media_app/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class NewUserForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2")

    def save(self, commit=True):
        user = super(NewUserForm, self).save(commit=False)
        user.email = self.cleaned_data['email']
        if commit:
            user.save()
        return user

honours_project/media_app/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse, HttpResponseBadRequest
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.db.models import Subquery, OuterRef
from .forms import NewUserForm
from media_app.models import Media, MediaList, Ratings, User
from surprise import KNNBasic, Dataset, Reader, SVD
from surprise.model_selection import cross_validate, LeaveOneOut
from collections import defaultdict
import heapq
from operator import itemgetter
import pandas as pd
import requests
from decouple import config
from urllib.parse import urljoin

# Image that shows up when no cover is provided
PLACEHOLDER_IMG_URL = 'https://via.placeholder.com/300x444.png?text=No+Image+Available'

# Create your views here.

# Home view
def home(request):
    if request.user.is_authenticated:
        media_in_medialist = Media.objects.filter(medialist__user=request.user)
        unrated_media = Media.objects.filter(
            id__in=Subquery(media_in_medialist.values('id')),).exclude(ratings__user=request.user)
        context = {
            'user': request.user,
            'unrated_media': unrated_media,
        }
        return render(request, 'homepage.html', context)
    else:
        return render(request, 'homepage.html', {'user': request.user})

# Ratings view
def ratings(request):
    return render(request, 'ratings.html', {'user': request.user})

# Login view that redirects to home if user is already logged in
@login_required
def login_view(request):
    return redirect('home')

# Login view
def login_view(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('home')
        else:
            messages.error(request, 'Invalid username or password.')
    return render(request, 'login.html')

# Register view
def register_request(request):
    if request.method == "POST":
        form = NewUserForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('home')
        messages.error(request, "Unsuccessful registration, invalid information")
    form = NewUserForm()
    return render (request=request, template_name='register.html', context={"register_form": form })

# Log out view
def logout_view(request):
    logout(request)
    return redirect('home')

# Searches for media across the 4 APIs and renders the results
def search_media(request):
    if request.method == 'POST':
        # Get search query from the search bar
        query = request.POST.get('search')

        # Make request to OMDb API to search for movies
        movie_response = requests.get('http://www.omdbapi.com/', params={'s': query, 'type': 'movie', 'apikey': config("OMDB_KEY")})
        movie_data = movie_response.json()
        movies = movie_data.get('Search', [])
        for movie in movies:
            # Make a request for each individual movie to get the plot
            movie_id = movie['imdbID']
            movie_detail_response = requests.get('http://www.omdbapi.com/', params={'i': movie_id, 'apikey': config("OMDB_KEY")})
            movie_detail_data = movie_detail_response.json()
            movie['Plot'] = movie_detail_data.get('Plot', '')
            # Replace the cover URL with the placeholder image URL if not available
            if movie['Poster'] == 'N/A':
                movie['Poster'] = PLACEHOLDER_IMG_URL

        # Make request to OMDb API to search for TV shows
        tv_response = requests.get('http://www.omdbapi.com/', params={'s': query, 'type': 'series', 'apikey': config("OMDB_KEY")})
        tv_data = tv_response.json()
        tv_shows = tv_data.get('Search', [])
        for tv_show in tv_shows:
            # Make a request for each individual TV show to get the plot
            tv_show_id = tv_show['imdbID']
            tv_show_detail_response = requests.get('http://www.omdbapi.com/', params={'i': tv_show_id, 'apikey': config("OMDB_KEY")})
            tv_show_detail_data = tv_show_detail_response.json()
            tv_show['Plot'] = tv_show_detail_data.get('Plot', '')
            if 'N/A' in tv_show['Poster']:
                tv_show['Poster'] = PLACEHOLDER_IMG_URL

        # Make request to IGDB API to search for games
        igdb_response = requests.post('https://api.igdb.com/v4/games', headers={
            'Client-ID': config("IGDB_CLIENT_ID"),
            'Authorization': f'Bearer {config("IGDB_ACCESS_TOKEN")}'
        }, data=f'search "{query}"; fields name, cover.url, summary; limit 5;')
        igdb_data = igdb_response.json()
        games = igdb_data

        # Replace the cover URL with the placeholder image URL if not available
        for game in games:
            if 'cover' in game and game['cover']:
                if 'url' in game['cover'] and game['cover']['url']:
                    game['cover_url'] = game['cover']['url']
                else:
                    game['cover_url'] = PLACEHOLDER_IMG_URL
            else:
                game['cover_url'] = PLACEHOLDER_IMG_URL

        # Make a request to Google Books for books
        google_books_api_key = config("GOOGLE_BOOKS_KEY")
        google_books_url = f"https://www.googleapis.com/books/v1/volumes?key={google_books_api_key}&q={query}&maxResults=5"
        google_books_response = requests.get(google_books_url)
        google_books_data = google_books_response.json()

        # Make a request to MusicBrainz API to search for albums
        musicbrainz_response = requests.get('https://musicbrainz.org/ws/2/release-group/', params={'query': query, 'type': 'album', 'limit': 5}, headers={'Accept': 'application/json'})
        musicbrainz_data = musicbrainz_response.json()
        
        # Parse the responses and get the media information
        movies = movie_data.get('Search', [])[:5] if movie_response.ok and movie_data.get('Response') == 'True' else []
        tv_shows = tv_data.get('Search', [])[:5] if tv_response.ok and tv_data.get('Response') == 'True' else []
        games = igdb_response.json() if igdb_response.ok else []
        books = google_books_data.get('items', []) if google_books_response.ok and google_books_data.get('totalItems', 0) > 0 else []
        albums = []
        if musicbrainz_response.ok and musicbrainz_data.get('release-groups'):
            for release_group in musicbrainz_data['release-groups'][:5]:
                album = {}
                album['title'] = release_group['title']
                album['artist'] = release_group['artist-credit'][0]['artist']['name']
                album['cover_url'] = urljoin('https://coverartarchive.org/release-group/', release_group['id']) + '/front-500'
                albums.append(album)


        media = {'movies': movies, 'tv_shows': tv_shows, 'games': games, 'books': books, 'albums': albums}

        # Render the results
        return render(request, 'search_results.html', {'media': media})
        
    # If the request method is GET, render the template
    return render(request, 'search.html')

# Add item to user's media list
def add_to_list(request):
    if request.method == 'POST':
        title = request.POST['title']
        poster_url = request.POST['poster_url']
        description = request.POST.get('description')
        media_type = request.POST.get('media_type')

        # Check if media with same title and type already exists
        existing_media = Media.objects.filter(title=title, media_type=media_type).first()

        if existing_media:
            # If media already exists, add it to the user's media list
            media_list, created = MediaList.objects.get_or_create(user=request.user)
            media_list.media.add(existing_media)
        else:
            # If media does not exist, create it and add it to the user's media list
            new_media = Media(title=title, poster_url=poster_url, description=description, media_type=media_type)
            new_media.save()
            media_list, created = MediaList.objects.get_or_create(user=request.user)
            media_list.media.add(new_media)

        return redirect('home')

# Removes item from user's media list and rating from ratings database
def remove_from_list(request, medialist_id, media_id):
    medialist = get_object_or_404(MediaList, id=medialist_id, user=request.user)
    media = get_object_or_404(Media, id=media_id)
    rating = Ratings.objects.filter(user=request.user, media=media).first()  # Get rating
    if rating:
        rating.delete()  # Delete rating if it exists
    medialist.media.remove(media)
    return redirect('home')

# Adds rating to Ratings database
def add_rating(request):
    if request.method != 'POST':
        return HttpResponseBadRequest("Invalid request method")
    
    user_id = request.POST.get('user_id')
    media_id = request.POST.get('media_id')
    score = request.POST.get('score')
    
    user = get_object_or_404(User, id=user_id)
    media = get_object_or_404(Media, id=media_id)
    
    # Try to get an existing rating for this user and media
    rating = Ratings.objects.filter(user=user, media=media).first()
    if rating:
        # Update the existing rating
        rating.score = score
        rating.save()
        return redirect('home')
    
    # Create a new rating
    rating = Ratings.objects.create(user=user, media=media, score=score)
    return redirect('home')

# User based collaborative filtering algorithm that recommends N media items
def recommend_media(request):
    # Set current user (user the algorithm is running recommendations for)
    currentUser = request.user.id

    # Check if user has rated anything

honours_project/media_app/templates/base.html
<!DOCTYPE html>

{% load static %}

<html>
  <head>
    <meta charset="UTF-8" />
    <title>{% block title %}Media Tracker{% endblock %}</title>
    <link
      rel="shortcut icon"
      type="image/png"
      href="{% static 'favicon.ico' %}"
    />
    <link rel="stylesheet" type="text/css" href="{% static 'styles.css' %}" />
    <link rel="stylesheet"
    href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
    integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"
    crossorigin="anonymous">
  </head>
  <body>
    {% include 'sidebar.html' %}
    <div class="content">
      <script
        src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"
      ></script>
      <script
        src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNVe6Xf"
        crossorigin="anonymous"
      ></script>
      <script
        src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"
      ></script>
      {% block content %}{% endblock %}
    </div>
  </body>
</html>

honours_project/media_app/templates/homepage.html
<!DOCTYPE html>
{% extends 'base.html' %} {% block content %}
<html>
  <body>
    {% if user.is_authenticated %}
    <h3>Welcome, {{ user.username }}!</h3>

    {% if user.medialist_set.all %}
    <h2>My List</h2>
    <div class="row">
      {% for medialist in user.medialist_set.all %}
      {% for media in unrated_media %}
      <div class="col-12 col-md-2">
        <div class="card mb-4 box-shadow">
          <img class="card-img-top" src="{{ media.poster_url }}" alt="{{ media.title }}" style="width: 100%" />
          <div class="card-body">
            <h5 class="card-title">{{ media.title }}</h5>
            <p class="card-text">{{ media.description|slice:":100" }}{% if media.description|length > 100 %}...{% endif %}</p>

            {% for rating in media.ratings_set.all %} {% if rating.user == user %}
            <p>Your rating: {{ rating.score }}</p>
            {% endif %} {% endfor %}

            <form action="{% url 'add_rating' %}" method="post">
              {% csrf_token %}
              <input type="hidden" name="user_id" value="{{ user.id }}" />
              <input type="hidden" name="media_id" value="{{ media.id }}" />
              <div class="rating">
                <select name="score">
                  <option value="10">10 stars</option>
                  <option value="9">9 stars</option>
                  <option value="8">8 stars</option>
                  <option value="7">7 stars</option>
                  <option value="6">6 stars</option>
                  <option value="5">5 stars</option>
                  <option value="4">4 stars</option>
                  <option value="3">3 stars</option>
                  <option value="2">2 stars</option>
                  <option value="1">1 star</option>
                </select>
              </div>
              <button type="submit" class="btn btn-primary">Rate</button>
            </form>            
          </div>
        </div>
      </div>
      {% endfor %} {% endfor %}
    </div>
    {% endif %} {% else %}
    <p>Please log in or register</p>
    {% endif %}
  </body>
</html>
{% endblock %}

honours_project/media_app/templates/login.html
{% extends 'base.html' %}

{% block content %}
  <h1>Login</h1>
  {% if messages %}
    <ul class="messages">
      {% for message in messages %}
        <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
      {% endfor %}
    </ul>
  {% endif %}
  <form method="post">
    {% csrf_token %}
    <div>
      <label for="id_username">Username:</label>
      <input type="text" name="username" id="id_username">
    </div>
    <div>
      <label for="id_password">Password:</label>
      <input type="password" name="password" id="id_password">
    </div>
    <button type="submit">Login</button>
  </form>
  <a href="{% url 'register' %}" class="btn btn-primary">Click here to register</a>
{% endblock %}

honours_project/media_app/templates/logout.html
{% extends 'base.html' %} {% if user.is_authenticated %}
<a href="{% url 'logout' %}">Log Out</a>
{% endif %}

honours_project/media_app/templates/ratings.html
<!DOCTYPE html>
{% extends 'base.html' %} {% block content %}
<html>
  <body>
    {% if user.is_authenticated %}
    {% if user.medialist_set.all %}
    <h2>My Ratings</h2>
    <div class="row">
      {% for medialist in user.medialist_set.all %} {% for media in medialist.media.all %} {% for rating in media.ratings_set.all %} {% if rating.user == user %}
      <div class="col-12 col-md-2">
        <div class="card mb-4 box-shadow">
          <img class="card-img-top" src="{{ media.poster_url }}" alt="{{ media.title }}" style="width: 100%" />
          <div class="card-body">
            <h5 class="card-title">{{ media.title }}</h5>
            <p class="card-text">{{ media.description|slice:":100" }}{% if media.description|length > 100 %}...{% endif %}</p>

            {% for rating in media.ratings_set.all %} {% if rating.user == user %}
            <p>Your rating: {{ rating.score }}</p>
            {% endif %} {% endfor %}

            <form action="{% url 'add_rating' %}" method="post">
              {% csrf_token %}
              <input type="hidden" name="user_id" value="{{ user.id }}" />
              <input type="hidden" name="media_id" value="{{ media.id }}" />
              <div class="rating">
                <select name="score">
                  <option value="10">10 stars</option>
                  <option value="9">9 stars</option>
                  <option value="8">8 stars</option>
                  <option value="7">7 stars</option>
                  <option value="6">6 stars</option>
                  <option value="5">5 stars</option>
                  <option value="4">4 stars</option>
                  <option value="3">3 stars</option>
                  <option value="2">2 stars</option>
                  <option value="1">1 star</option>
                </select>
              </div>
              <button type="submit" class="btn btn-primary">Rate</button>
            </form>
            <form action="{% url 'remove_from_list' medialist.id media.id %}" method="post">
              {% csrf_token %}
              <button type="submit" class="btn btn-danger">Remove</button>
            </form>
          </div>
        </div>
      </div>
      {% endif %} {% endfor %}
      {% endfor %} {% endfor %}
    </div>
    {% endif %} {% else %}
    <p>Please log in or register</p>
    {% endif %}
  </body>
</html>
{% endblock %}

honours_project/media_app/templates/recommendations.html
{% extends "base.html" %}

{% block content %}
<h1>Top 5 Recommendations for You:</h1>
  <div class="row">
    {% for rec in media %}
      <div class="col-md-2">
        <div class="card mb-2">
          <img class="card-img-top" src="{{ rec.media_poster }}" alt="{{ rec.media_name }}">
          <div class="card-body">
            <h5 class="card-title">{{ rec.media_name }}</h5>
            <p class="card-text">{{ rec.media_description }}</p>
            <p class="card-text">Score: {{ rec.score }}</p>
          </div>
        </div>
      </div>
    {% endfor %}
  </div>
{% endblock %}

honours_project/media_app/templates/register.html
{% extends 'base.html' %} {% load crispy_forms_tags %} {% block content %}
<div class="container py-5">
  <h1>Register</h1>
  <form method="POST">
    {% csrf_token %} {{ register_form|crispy }}
    <button class="btn btn-primary" type="submit">Register</button>
  </form>
  <p class="text-center">
    If you already have an account, <a href="/login">login</a> instead.
  </p>
</div>

{% endblock %}

honours_project/media_app/templates/search.html
{% extends 'base.html' %} {% block content %}
<h1>Media Search</h1>

<form method="post">
  {% csrf_token %}
  <input type="text" name="search" placeholder="Search for media..." />
  <button type="submit">Search</button>
</form>
{% endblock %}

honours_project/media_app/templates/search_results.html
{% extends 'base.html' %} {% block content %}
<div class="container">
  <h1>Search Results</h1>

  {% if media.movies %}
  <h2>Movies</h2>
  <p>Provided by OMDb</p>
  <div class="row">
    {% for medium in media.movies %}
    <div class="col-12 col-md-2">
      <div class="card mb-4 box-shadow">
        <img class="card-img-top" src="{{ medium.Poster }}" alt="{{ medium.Title }}" style="width: 100%" />
        <div class="card-body">
          <h5 class="card-title">{{ medium.Title }}</h5>
          <p class="card-text">{{ medium.Plot|slice:":100" }}{% if medium.Plot|length > 100 %}...{% endif %}</p>
          <form method="POST" action="{% url 'add_to_list' %}">
            {% csrf_token %}
            <input type="hidden" name="title" value="{{ medium.Title }}" />
            <input type="hidden" name="poster_url" value="{{ medium.Poster }}" />
            <input type="hidden" name="description" value="{{ medium.Plot }}" />
            <input type="hidden" name="media_type" value="movie" />
            <button type="submit" class="btn btn-primary">Add to List</button>
          </form>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
  {% endif %} {% if media.tv_shows %}
  <h2>TV Shows</h2>
  <p>Provided by OMDb</p>
  <div class="row mt-4">
    {% for medium in media.tv_shows %}
    <div class="col-12 col-md-2">
      <div class="card mb-4 box-shadow">
        <img class="card-img-top" src="{{ medium.Poster }}" alt="{{ medium.Title }}" style="width: 100%" />
        <div class="card-body">
          <h5 class="card-title">{{ medium.Title }}</h5>
          <p class="card-text">{{ medium.Plot|slice:":100" }}{% if medium.Plot|length > 100 %}...{% endif %}</p>
          <form method="POST" action="{% url 'add_to_list' %}">
            {% csrf_token %}
            <input type="hidden" name="title" value="{{ medium.Title }}" />
            <input type="hidden" name="poster_url" value="{{ medium.Poster }}" />
            <input type="hidden" name="description" value="{{ medium.Plot }}" />
            <input type="hidden" name="media_type" value="tv_show" />
            <button type="submit" class="btn btn-primary">Add to List</button>
          </form>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
  {% endif %} {% if media.games %}
  <h2>Games</h2>
  <p>Provided by IGDB</p>
  <div class="row mt-4">
    {% for medium in media.games %}
    <div class="col-12 col-md-2">
      <div class="card mb-4 box-shadow">
        <img class="card-img-top" src="{{ medium.cover.url }}" alt="{{ medium.name }}" style="width: 100%" />
        <div class="card-body">
          <h5 class="card-title">{{ medium.name }}</h5>
          <p class="card-text">{{ medium.summary|slice:":100" }}{% if medium.summary|length > 100 %}...{% endif %}</p>
          <form method="POST" action="{% url 'add_to_list' %}">
            {% csrf_token %}
            <input type="hidden" name="title" value="{{ medium.name }}" />
            <input type="hidden" name="poster_url" value="{{ medium.cover.url }}" />
            <input type="hidden" name="description" value="{{ medium.summary }}" />
            <input type="hidden" name="media_type" value="game" />
            <button type="submit" class="btn btn-primary">Add to List</button>
          </form>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
  {% endif %} {% if media.books %}
  <h2>Books</h2>
  <p>Provided by Google Books</p>
  <div class="row mt-4">
    {% for medium in media.books %}
    <div class="col-12 col-md-2">
      <div class="card mb-4 box-shadow">
        <img class="card-img-top" src="{{ medium.volumeInfo.imageLinks.thumbnail }}" alt="{{ medium.volumeInfo.title }}" style="width: 100%" />
        <div class="card-body">
          <h5 class="card-title">{{ medium.volumeInfo.title }}</h5>
          <p class="card-text">{{ medium.volumeInfo.description|slice:":100" }}{% if medium.volumeInfo.description|length > 100 %}...{% endif %}</p>
          <form method="POST" action="{% url 'add_to_list' %}">
            {% csrf_token %}
            <input type="hidden" name="title" value="{{ medium.volumeInfo.title }}" />
            <input type="hidden" name="poster_url" value="{{ medium.volumeInfo.imageLinks.thumbnail }}" />
            <input type="hidden" name="description" value="{{ medium.volumeInfo.description }}" />
            <input type="hidden" name="media_type" value="book" />
            <button type="submit" class="btn btn-primary">Add to List</button>
          </form>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
  {% endif %} {% if media.albums %}
  <h2>Albums</h2>
  <p>Provided by MusicBrainz</p>
  <div class="row mt-4">
    {% for medium in media.albums %}
    <div class="col-12 col-md-2">
      <div class="card mb-4 box-shadow">
        <img class="card-img-top" src="{{ medium.cover_url }}" alt="{{ medium.title }}" style="width: 100%" />
        <div class="card-body">
          <h5 class="card-title">{{ medium.title }}</h5>
          <p class="card-text">{{ medium.release_date }}</p>
          <form method="POST" action="{% url 'add_to_list' %}">
            {% csrf_token %}
            <input type="hidden" name="title" value="{{ medium.title }}" />
            <input type="hidden" name="poster_url" value="{{ medium.cover_url }}" />
            <input type="hidden" name="description" value="{{ medium.release_date }}" />
            <input type="hidden" name="media_type" value="album" />
            <button type="submit" class="btn btn-primary">Add to List</button>
          </form>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
  {% endif %} {% if not media.movies and not media.tv_shows and not media.games and not media.books and not media.albums %}
  <p>No results found.</p>
  {% endif %}
</div>
{% endblock %}

honours_project/media_app/templates/sidebar.html
<div class="sidebar">
  <ul>
    <li><a href="{% url 'home' %}">Home</a></li>
    {% if user.is_authenticated %}
    <li><a href="{% url 'search_media' %}">Search</a></li>
    <li><a href="{% url 'ratings' %}">Ratings</a></li>
    <li><a href="{% url 'recommend_media' %}">Recommendations</a></li>
    <li><a href="{% url 'logout' %}">Logout</a></li>
    {% else %}
    <li><a href="{% url 'login' %}">Login / Register</a></li>
    {% endif %}
  </ul>
</div>